const path = require('path');
const fs = require('fs');

module.exports = {
  'init': function(browser) {
    browser
      .url('file://' + path.join(__dirname, 'index.html'))
      .waitForElementVisible('body', 1000)
      .pause(20)
      .moveToElement('canvas', 20, 20)
      .mouseButtonDown(0)
      .mouseButtonUp(0)
      .moveToElement('#side .fill-panel .line .pick', 10, 10)
      .mouseButtonDown(0)
      .mouseButtonUp(0)
      .assert.cssProperty('#main .gradient .l', 'left', '150px')
      .assert.cssProperty('#main .gradient .l', 'top', '100px')
      .assert.cssProperty('#main .gradient .l', 'transform', 'matrix(-0.832051, -0.554699, 0.554699, -0.832051, 0, -4)')
      .assert.cssClassPresent('#main .gradient span[title="0"]', 'cur')
      .assert.cssProperty('#main .gradient span[title="0"]', 'left', '150px')
      .assert.cssProperty('#main .gradient span[title="0"]', 'top', '100px')
      .assert.cssProperty('#main .gradient span[title="0"]', 'backgroundColor', 'rgba(255, 0, 0, 1)')
      .assert.cssProperty('#main .gradient span[title="1"]', 'left', '0px')
      .assert.cssProperty('#main .gradient span[title="1"]', 'top', '0px')
      .assert.cssProperty('#main .gradient span[title="1"]', 'backgroundColor', 'rgba(0, 0, 255, 1)')

      .moveToElement('#main .gradient', 90, 60)
      .mouseButtonDown(0)
      .mouseButtonUp(0)
      .assert.cssProperty('#main .gradient span[title="1"]', 'left', '89.9062px')
      .assert.cssProperty('#main .gradient span[title="1"]', 'top', '59.9375px')
      .assert.cssProperty('#main .gradient span[title="1"]', 'backgroundColor', 'rgba(153, 0, 102, 1)')

      .keys(browser.Keys.ESCAPE)
      .keys(browser.Keys.NULL)
      .moveToElement('canvas', 20, 220)
      .mouseButtonDown(0)
      .mouseButtonUp(0)
      .moveToElement('#side .fill-panel .line .pick', 10, 10)
      .mouseButtonDown(0)
      .mouseButtonUp(0)
      .assert.cssProperty('#main .gradient .l', 'left', '75px')
      .assert.cssProperty('#main .gradient .l', 'top', '50px')
      .assert.cssProperty('#main .gradient .l', 'transform', 'matrix(-0.832051, -0.554699, 0.554699, -0.832051, 0, -4)')
      .assert.cssProperty('#main .gradient span[title="0"]', 'left', '75px')
      .assert.cssProperty('#main .gradient span[title="0"]', 'top', '50px')
      .assert.cssProperty('#main .gradient span[title="0"]', 'backgroundColor', 'rgba(255, 0, 0, 1)')
      .assert.cssProperty('#main .gradient span[title="1"]', 'left', '0px')
      .assert.cssProperty('#main .gradient span[title="1"]', 'top', '0px')
      .assert.cssProperty('#main .gradient span[title="1"]', 'backgroundColor', 'rgba(0, 0, 255, 1)')
      .assert.cssProperty('#main .gradient .e', 'left', '100.172px')
      .assert.cssProperty('#main .gradient .e', 'top', '12.2188px')

      .moveToElement('#main .gradient', 75, 50)
      .mouseButtonDown(0)
      .moveToElement('#main .gradient', 150, 100)
      .mouseButtonUp(0)
      .assert.cssProperty('#main .gradient span[title="1"]', 'left', '75px')
      .assert.cssProperty('#main .gradient span[title="1"]', 'top', '50px')

      .keys(browser.Keys.ESCAPE)
      .keys(browser.Keys.NULL)
      .moveToElement('canvas', 20, 260)
      .mouseButtonDown(0)
      .mouseButtonUp(0)
      .moveToElement('#side .fill-panel .line .pick', 20, 320)
      .mouseButtonDown(0)
      .mouseButtonUp(0)
      .assert.cssProperty('#main .gradient span[title="0"]', 'left', '0px')
      .assert.cssProperty('#main .gradient span[title="0"]', 'top', '50px')
      .assert.cssProperty('#main .gradient span[title="0"]', 'backgroundColor', 'rgba(255, 0, 0, 1)')
      .assert.cssProperty('#main .gradient span[title="1"]', 'left', '0px')
      .assert.cssProperty('#main .gradient span[title="1"]', 'top', '50px')
      .assert.cssProperty('#main .gradient span[title="1"]', 'backgroundColor', 'rgba(0, 0, 255, 1)')

      .moveToElement('#main .gradient', 18, 0)
      .mouseButtonDown(0)
      .mouseButtonUp(0)
      .assert.cssProperty('#main .gradient span[title="1"]', 'left', '18px')
      .assert.cssProperty('#main .gradient span[title="1"]', 'top', '0px')
      .assert.cssProperty('#main .gradient span[title="1"]', 'backgroundColor', 'rgba(0, 0, 255, 1)')

      .end();
  }
};
