const path = require('path');
const fs = require('fs');

module.exports = {
  'init': function(browser) {
    browser
      .url('file://' + path.join(__dirname, 'index.html'))
      .waitForElementVisible('body', 1000)
      .pause(20)
      .moveToElement('canvas', 50, 50)
      .click('#button4')
      .assert.value('#base64', '[0]')
      .doubleclick()
      .click('#button4')
      .assert.value('#base64', '[1,"c"]')
      .doubleclick()
      .click('#button4')
      .assert.value('#base64', '[2,"a"]')
      .doubleclick()
      .click('#button4')
      .assert.value('#base64', '[3,"1"]')
      .assert.cssProperty('#main .geometry', 'display', 'none')
      .doubleclick()
      .assert.cssProperty('#main .geometry', 'display', 'block')

      .keys(browser.Keys.ESCAPE)
      .keys(browser.Keys.NULL)
      .assert.cssProperty('#main .geometry', 'display', 'none')
      .click('#button4')
      .assert.value('#base64', '[4,"1"]')
      .keys(browser.Keys.ESCAPE)
      .keys(browser.Keys.NULL)
      .click('#button4')
      .assert.value('#base64', '[5,"a"]')
      .keys(browser.Keys.ESCAPE)
      .keys(browser.Keys.NULL)
      .click('#button4')
      .assert.value('#base64', '[6,"c"]')
      .keys(browser.Keys.ESCAPE)
      .keys(browser.Keys.NULL)
      .click('#button4')
      .assert.value('#base64', '[7,"d"]')
      .keys(browser.Keys.ESCAPE)
      .keys(browser.Keys.NULL)
      .click('#button4')
      .assert.value('#base64', '[8]')

      .click('#tree span.name[title="c"]')
      .click('#button4')
      .assert.value('#base64', '[9,"c"]')
      .keys(browser.Keys.META)
      .click('#tree span.name[title="d"]')
      .keys(browser.Keys.NULL)
      .click('#button4')
      .assert.value('#base64', '[10,"c"]')
      .keys(browser.Keys.META)
      .click('#tree span.name[title="b"]')
      .keys(browser.Keys.NULL)
      .click('#button4')
      .assert.value('#base64', '[11,"b"]')

      .keys(browser.Keys.META)
      .click('#tree span.name[title="2"]')
      .keys(browser.Keys.NULL)
      .click('#button4')
      .assert.value('#base64', '[[12,"b"],[12,"2"]]')
      .keys(browser.Keys.ESCAPE)
      .keys(browser.Keys.NULL)
      .click('#button4')
      .assert.value('#base64', '[13,"a"]')

      .end();
  }
};
